### ISSUE TITLE
bsg_cache.v ready_o may be yumi_o

### ISSUE THREAD

**Issue by BrendenPage** [bespoke-silicon-group/basejump_stl#605]
As seen in the below snippet, the ready_o signal depends upon the v_i signal in all execution paths. Conceptually, it does not feel like a yumi_o signal as in this case it does not seem to primarily indicate to a producer that an instruction or data packet has been consumed, but acts more as a ready_and signal. On a tl miss, or when the store buffer entry is full, however, the ready_o signal depends on the v_i. 

https://github.com/bespoke-silicon-group/basejump_stl/blob/master/bsg_cache/bsg_cache.v#L980-L995

However, there is a place in bsg_cache that depends on ready_o and not on v_i, possibly leading to some issues shown below. Therefore, I would like to know what actions should be taken, either to convert the signal to more properly present as yumi or ready_and.

https://github.com/bespoke-silicon-group/basejump_stl/blob/master/bsg_cache/bsg_cache.v#L147

An issue opened earlier by dan of the same topic:

https://github.com/bespoke-silicon-group/basejump_stl/issues/347

**Comment by dpetrisko** [comment]
Hi @taylor-bsg @tommydcjung can we get some guidance on this? This is a handshake problem because if we connect bsg_cache to a demanding ready->valid module there will be a combinational loop. I see a few solutions:
- disable the tl_we if tag_op optimization and only ready if TL is available
- Change the interface to yumi_o and update _to_cache modules
- Define a new type of handshake _then_ready which is different than yumi by virtue of not acting as an ack but restricting the handshakes it attaches to be helpful 


My preference is probably for 1 as I don’t think tagst is ever used in a mixed workload where performance is important. Thoughts?

**Comment by dpetrisko** [comment]
Resolved
